# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170209_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='song_list',
            new_name='songs',
        ),
    ]
