# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170212_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
