# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170226_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='created_by',
            new_name='user',
        ),
    ]
