# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170226_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_uri',
            field=models.TextField(default=b''),
        ),
    ]
