# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
