# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20161002_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='refresh_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
