# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20161017_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_background_image',
            field=models.ImageField(null=True, upload_to='user_uploads'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='user_uploads'),
        ),
    ]
