# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20161120_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_background_image',
            new_name='profile_background_picture',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
